[green_agent]
agentbeats_id = "019b9edf-c1b5-7422-b35d-c68efda0d8db"
port = 8001
env = { NEBIUS_API_KEY = "${NEBIUS_API_KEY}", LOG_LEVEL = "INFO", SETTINGS_MODEL = "nebius/openai/gpt-oss-20b", QUESTION_MODEL = "nebius/openai/gpt-oss-20b", RESPONSE_MODEL = "nebius/Qwen/Qwen3-30B-A3B-Instruct-2507", RUBRIC_MODEL = "nebius/Qwen/Qwen3-30B-A3B-Instruct-2507", EVAL_1_MODEL = "nebius/Qwen/Qwen3-30B-A3B-Instruct-2507", SCORE_AGG_MODEL = "nebius/Qwen/Qwen3-30B-A3B-Instruct-2507" }

[[participants]]
agentbeats_id = "019b9f87-7738-7f01-8dfd-a2ad4284da66"
name = "PersonaGymAgent"
port = 9020
env = { NEBIUS_API_KEY = "${NEBIUS_API_KEY}", LOG_LEVEL = "INFO", PERSONAGYM_MODEL = "nebius/meta-llama/Llama-3.3-70B-Instruct" }

[config]
persona = "A 34-year-old scientist from London who is a social media influencer."
